{
 "title": "Cluster Hub Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Managed clusters #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rancher_cluster_status{Name!=\"local\"})"
    }
   ]
  },
  {
   "title": "Cluster states over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(cluster_connected)", "legendFormat": "Connected" },
    { "expr": "count(cluster_connected == 0)", "legendFormat": "Disconnected" },
    {
     "expr": "sum(rancher_cluster_condition_disk_pressure)",
     "legendFormat": "Disk pressure"
    },
    {
     "expr": "sum(rancher_cluster_condition_memory_pressure)",
     "legendFormat": "Memory pressure"
    },
    {
     "expr": "sum(rancher_cluster_condition_ready)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(rancher_cluster_condition_ready == 0)",
     "legendFormat": "Not ready"
    }
   ]
  },
  {
   "title": "Cluster readiness",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rancher_cluster_condition_ready)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(rancher_cluster_condition_ready == 0)",
     "legendFormat": "Not ready"
    }
   ]
  },
  {
   "title": "Managed clusters",
   "type": "suse-edgehub-panel",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "rancher_cluster_status{DisplayName!=\"local\"}"
    },
    { "expr": "cluster_connected" },
    {
     "expr": "rancher_cluster_condition_disk_pressure"
    },
    {
     "expr": "rancher_cluster_condition_memory_pressure"
    },
    {
     "expr": "rancher_cluster_condition_ready"
    }
   ]
  },
  {
   "title": "Cluster versions",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Version) (rancher_cluster_status{DisplayName!=\"local\"})",
     "legendFormat": "{{Version}}"
    }
   ]
  },
  {
   "title": "Spoke clusters map",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count by(cluster_name, RancherServerURL, latitude, longitude) (rancher_cluster_status{cluster_name=~\"spoke.*\"})",
     "legendFormat": "Clusters count"
    }
   ]
  },
  {
   "title": "Spoke clusters",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "count by(cluster_name, RancherServerURL) (rancher_cluster_status)",
     "legendFormat": "Clusters count"
    }
   ]
  }
 ]
}