# https://grafana.com/tutorials/provision-dashboards-and-data-sources/#provision-a-data-source

apiVersion: 1

datasources:
  - name: TestData
    type: testdata
  - name: Mimir
    type: prometheus
    url: http://mimir-192.168.122.223.sslip.io/prometheus
    uid: mimir
    isDefault: true

